TT_INTEIRO	= 'INTEIRO'
TT_REAL		 = 'REAL'
TT_LOGICO	 = 'LÓGICO'
TT_TEXTO		= 'TEXTO'
TT_VER		= 'VERDADEIRO'
TT_FAL		= 'FALSO'
TT_IDE		= 'IDENTIFICADOR'
TT_PCH		= 'PALAVRACHAVE'

TT_PONTO		= 'PONTO'
TT_VIRGULA		= 'VÍRGULA'
TT_SETA		 = 'SETA'
TT_NOVALINHA	= 'NOVALINHA'
TT_FIM		= 'FIM'

TT_MAI		= 'ADIÇÃO'
TT_MEN		= 'SUBTRAÇÃO'
TT_MUL		= 'MULTIPLICAÇÃO'
TT_DIV		= 'DIVISÃO'
TT_POT		= 'POTENCIAÇÃO'
TT_RAD		= 'RADICIAÇÃO'
TT_LOG		= 'LOGARITMO'
TT_RES		= 'RESTO'

TT_PI		 = 'VALOR DE PI'

TT_IGU 		= 'IGUAL A'
TT_EIG		= 'É IGUAL A'
TT_DIF		= 'DIFERENTE'
TT_MIQ		= 'MAIOR QUE'
TT_MNQ		= 'MENOR QUE'
TT_MIQIGU	 = 'MAIOR OU IGUAL A'
TT_MNQIGU	 = 'MENOR OU IGUAL A'

TT_INTCONJ	 = 'INTERSEÇÃO'
TT_DENCONJ	 = 'PERTENCE A'
TT_FORCONJ	 = 'NÃO PERTENCE A'

TT_ABRPARENT	= 'ABRE PARÊNTESES'
TT_FECPARENT	= 'FECHA PARÊNTESES'
TT_ABRCOLCHE	= 'ABRE COLCHETES'
TT_FECCOLCHE	= 'FECHA COLCHETES'
TT_ABRCHAVES	= 'ABRE CHAVES'
TT_FECCHAVES	= 'FECHA CHAVES'

TT_OPERAÇÕES = {
	'MAIS': TT_MAI,'MENOS': TT_MEN,'VEZES': TT_MUL,'DIVIDIDO': TT_DIV,'RESTO': TT_RES,'ELEVADO': TT_POT,'RAÍZ': TT_RAD,'RAIZ': TT_RAD,
	'IGUAL': TT_IGU,'DIFERENTE': TT_DIF,'MAIOR': TT_MIQ,'MENOR': TT_MNQ,
	'INTERSEÇÃO': TT_INTCONJ,'INTERSEÇAO': TT_INTCONJ,'INTERSECÃO': TT_INTCONJ,'INTERSECAO': TT_INTCONJ,
	'PERTENCE': TT_DENCONJ,'NÃOPERTENCE': TT_FORCONJ,'NAOPERTENCE': TT_FORCONJ,'DENTRO': TT_DENCONJ,'FORA': TT_FORCONJ
}
TT_PALAVRASCHAVE = [
	'VAR','E','OU','NE','NOU','XOU','XNOU','=>','<=>','NÃO','NAO','SE','SENÃOSE','SENAOSE','SENÃO','SENAO',
	'PARA','CADA','PASSO','ENQUANTO','FUNÇÃO','FUNCÃO','FUNÇAO','FUNCAO',
	'ENTÃO','ENTAO','FIM','RETORNAR','CONTINUAR','QUEBRAR'
]